
extend: [ @base ]

include: [ blog, syntax ]
brand_name: Design.blog

nav:
  master: []
  toolbar:
    - label: Contact
      class: primary

meta:
  title: Emma Bennet / Design Engineering Blog
  title_template: %s / Emma Bennet
  author: Emma Bennet

site:
  origin: https://acme.org
  view_transitions: true

