
brand_name: LOGO

design:
  layers: [ base, ui, design ]

nav:
  master:
    - label: Docs
      url: /docs/

    - label: Blog
      url: /blog/

    - label: Pricing


  toolbar:
    - label: Call to action
      class: primary

  footer:
    - label: Docs
    - label: Blog
    - label: About
    - label: Legal
