
brand_name: LOGO
author: Jane Doe

include: [ forms.js ]

design:
  layers: [ base, ui, design ]

site:
  view_transitions: true

collections:
  blog:
    include: [ blog/ ]
    skip: [ skip ]
    sort: date desc

rss:
  enabled: true
  collection: blog

sitemap:
  enabled: true


nav:
  master:
    - label: Docs
      url: /docs/

    - label: Blog
      url: /blog/

    - label: Pricing

  toolbar:
    - label: Call to action
      class: primary

  footer:
    - label: Docs
    - label: Blog
    - label: About
    - label: Legal
