
topics:
  Essentials:
    - Getting started | /docs/
    - FAQ
    - Roadmap
    - Contributing

  Guides:
    - Global design system
    - Setting up page layout
    - Adding interactivity
    - Creating sites with AI
    - Single-page apps

  Reference:
    - Configuration
    - Command line interface
    - Page dependencies
    - Context data
    - Markdown syntax
    - Markdown extensions
    - HTML file types
    - HTML syntax
    - JavaScript enhancements
    - YAML syntax
    - State API
    - Nue internals

