topics:
  Essentials:
    - Getting started
    - FAQ
    - Roadmap
    - Nue internals
    - Contributing

  Guides:
    - Global design systems
    - Setting up page layout
    - Adding interactivity
    - Working with Claude
    - Single-page applications

  Reference:
    - Configuration
    - Command line interface
    - Page dependencies
    - Context data
    - Markdown syntax
    - Markdown extensions
    - HTML file types
    - HTML syntax
    - JavaScript enhancements
    - YAML syntax
    - State API
    - Nue internals

