
extend: [ @base ]

brand_name: Acme Inc.

meta:
  title_template: %s / Acme inc.
  description: Acme design agency

  # default author for blog entries
  author: Emma Bennet

nav:
  master:
    - label: Work
    - label: Services
    - label: Careers


  toolbar:
    - label: Contact us
      class: primary

  footer:
    - label: Industries
    - label: Culture
    - label: About
    - label: Legal


site:
  origin: https://acme.org
  view_transitions: true

sitemap:
  enabled: true

rss:
  title: Acme design/engineering blog
  collection: blog
  enabled: true

_collections:
  blog:
    include: [ blog/ ]
    skip: [ skip ]
    sort: date desc
