
extend: [ @base ]
brand_name: Acme Inc.

site:
  origin: https://acme.org
  view_transitions: true

meta:
  title_template: %s / Acme inc.
  description: Acme design agency

  # default author for blog entries
  author: Emma Bennet

nav:
  master:
    - label: Work
    - label: Guides
      url: /docs/
    - label: Careers


  toolbar:
    - label: Contact us
      class: primary

  footer:
    - label: Industries
    - label: Culture
    - label: About
    - label: Legal



