name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
      - packages/examples/**
      - packages/nuejs.org/**
  pull_request:
    paths-ignore:
      - .github/**
      - packages/examples/**
      - packages/nuejs.org/**
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.repository_owner == 'nuejs' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        tool: ['bun', 'node+jest']
        exclude:
          - { os: 'ubuntu-latest', tool: 'node+jest' }
          - { os: 'macos-latest', tool: 'node+jest' }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Testing `bun`
      - uses: oven-sh/setup-bun@v2
        if: ${{ matrix.tool == 'bun' }}

      - name: Install and test with Bun
        run: |
          bun -v
          bun install --no-save esbuild
          bun test --coverage
        if: ${{ matrix.tool == 'bun' }}

      # Testing `node+jest`
      - uses: actions/setup-node@v4
        if: ${{ matrix.tool == 'node+jest' }}

      - name: Install and test with Node
        run: |
          node -v && npm -v
          npm install --no-save jest jest-extended esbuild
          npm test -- --coverage
        if: ${{ matrix.tool == 'node+jest' }}
